# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
    brokers:
        - kafka1:19092
        - kafka2:19093
        - kafka3:19094

# server:
    # listenPort: 8080
