version: '3.7'

services:
    
    control-center:
        # https://github.com/confluentinc/cp-demo/blob/5.5.1-post/docker-compose.yml
        image: confluentinc/cp-enterprise-control-center:5.5.1
        depends_on:
            - zoo1
            - zoo2
            - zoo3
            - kafka1
            - kafka2
            - kafka3
        ports:
            - 9021:9021
        environment:
            CONTROL_CENTER_REST_LISTENERS: "http://0.0.0.0:9021"
            CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9093,kafka3:9094"
            CONTROL_CENTER_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
            CONTROL_CENTER_REPLICATION_FACTOR: 2
            CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
            CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 2
            CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
            CONTROL_CENTER_METRICS_TOPIC_REPLICATION: 2
            CONTROL_CENTER_METRICS_TOPIC_PARTITIONS: 1
            PORT: 9021

    zoo1:
        image: zookeeper:3.4.9
        restart: always
        hostname: zoo1
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        volumes:
            - ./enterprise-cluster-data/zoo1/data:/data
            - ./enterprise-cluster-data/zoo1/datalog:/datalog

    zoo2:
        image: zookeeper:3.4.9
        restart: always
        hostname: zoo2
        ports:
            - "2182:2182"
        environment:
            ZOO_MY_ID: 2
            ZOO_PORT: 2182
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        volumes:
            - ./enterprise-cluster-data/zoo2/data:/data
            - ./enterprise-cluster-data/zoo2/datalog:/datalog

    zoo3:
        image: zookeeper:3.4.9
        restart: always
        hostname: zoo3
        ports:
            - "2183:2183"
        environment:
            ZOO_MY_ID: 3
            ZOO_PORT: 2183
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        volumes:
            - ./enterprise-cluster-data/zoo3/data:/data
            - ./enterprise-cluster-data/zoo3/datalog:/datalog


    kafka1:
        image: confluentinc/cp-enterprise-kafka:5.5.1
        restart: always
        hostname: kafka1
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
            KAFKA_BROKER_ID: 1
            KAFKA_BROKER_RACK: "r1"
            KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
            KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
            CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
            CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka1:19092"
            CONFLUENT_METRICS_REPORTER_MAX_REQUEST_SIZE: 10485760
            CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: "false"
        volumes:
            - ./enterprise-cluster-data/kafka1/data:/var/lib/kafka/data
        depends_on:
            - zoo1
            - zoo2
            - zoo3

    kafka2:
        image: confluentinc/cp-enterprise-kafka:5.5.1
        restart: always
        hostname: kafka2
        ports:
            - "9093:9093"
        environment:
            KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
            KAFKA_BROKER_ID: 2
            KAFKA_BROKER_RACK: "r1"
            KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
            KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
            CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
            CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka2:19093"
            CONFLUENT_METRICS_REPORTER_MAX_REQUEST_SIZE: 10485760
            CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: "false"
        volumes:
            - ./enterprise-cluster-data/kafka2/data:/var/lib/kafka/data
        depends_on:
            - zoo1
            - zoo2
            - zoo3

    kafka3:
        image: confluentinc/cp-enterprise-kafka:5.5.1
        restart: always
        hostname: kafka3
        ports:
            - "9094:9094"
        environment:
            KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19094,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
            KAFKA_BROKER_ID: 3
            KAFKA_BROKER_RACK: "r1"
            KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
            KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
            CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
            CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka3:19094"
            CONFLUENT_METRICS_REPORTER_MAX_REQUEST_SIZE: 10485760
            CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: "false"
        volumes:
            - ./enterprise-cluster-data/kafka3/data:/var/lib/kafka/data
        depends_on:
            - zoo1
            - zoo2
            - zoo3
