version: "3.7"

services:

    consumer:
        build: .
        command: python3 /usr/app/consumer.py
        env_file:
            - .env
        volumes:
            - type: bind
              source: ./consumer.py
              target: /usr/app/consumer.py
              read_only: true
